### PR TITLE
Add filters!

### PR DESCRIPTION
**Pull request by notwaldorf**
I converted the list items in the "types of activities" list into buttons, so that you can filter by activity type! 🎉

### CODE REVIEW

**Comment by notwaldorf** [comment]
Done did a rebase! /cc @jlord, since I don't know how your notifications are set up :)

**Comment by jlord** [comment]
Oh my gosh, yay! This was on my wish-list (written inside my head) 🎉 👯 Thank you!

**Comment by jlord** [comment]
> since I don't know how your notifications are set up

Omg, thanks for reminding me you still have to follow your own repos 😓

**Comment by notwaldorf** [comment]
@jlord people be trying to fix your typo too! 😂

**Pull request merged**
